export type SlownikTerm = {
  term: string;
  slug: string;
  short: string;
  full: string;
  category: string;
};

export const TERMS: SlownikTerm[] = [
  { slug: 'stop-loss', term: 'Stop Loss (SL)', short: 'Zlecenie automatycznego zamknięcia pozycji przy określonej stracie.', full: 'Stop Loss to zlecenie ustawiane z góry, które automatycznie zamyka pozycję gdy cena osiągnie określony poziom. Chroni kapitał przed zbyt dużymi stratami. Podstawowe narzędzie zarządzania ryzykiem — nigdy nie handluj bez stop lossa.', category: 'Ogólne' },
  { slug: 'take-profit', term: 'Take Profit (TP)', short: 'Zlecenie automatycznego zamknięcia pozycji przy określonym zysku.', full: 'Take Profit to poziom ceny, przy którym pozycja zostaje automatycznie zamknięta z zyskiem. Pomaga realizować zyski bez konieczności ciągłego monitorowania rynku i eliminuje emocjonalne decyzje o za wczesnym zamknięciu.', category: 'Ogólne' },
  { slug: 'risk-reward', term: 'Risk/Reward (RR)', short: 'Stosunek potencjalnego zysku do potencjalnej straty w transakcji.', full: 'Risk/Reward to stosunek wielkości planowanego zysku (odległość do TP) do planowanej straty (odległość do SL). RR 1:2 oznacza że ryzykujesz 1 żeby zarobić 2. Nawet przy win rate 40% możesz być zyskowny mając dobre RR.', category: 'Ogólne' },
  { slug: 'win-rate', term: 'Win Rate', short: 'Procent zyskownych transakcji w stosunku do wszystkich zamkniętych.', full: 'Win Rate to odsetek transakcji zakończonych zyskiem. Np. 60% win rate oznacza że 6 na 10 transakcji wychodzi na plus. Sam win rate nic nie mówi — trader z 40% win rate i RR 1:3 zarabia więcej niż trader z 70% win rate i RR 1:0.8.', category: 'Ogólne' },
  { slug: 'profit-factor', term: 'Profit Factor', short: 'Stosunek sumy zysków do sumy strat. Wartość powyżej 1 oznacza zyskowność.', full: 'Profit Factor = suma wszystkich zysków / suma wszystkich strat. PF = 2.0 oznacza że na każdą złotówkę straty zarabiasz 2 złote. PF powyżej 1.5 jest uważany za dobry wynik. Im wyższy, tym bardziej solidna strategia.', category: 'Ogólne' },
  { slug: 'drawdown', term: 'Drawdown', short: 'Maksymalny spadek wartości konta od szczytu do dołka.', full: 'Drawdown mierzy jak głęboko spada wartość konta od ostatniego szczytu. Drawdown 10% oznacza że konto spadło o 10% z najwyższego punktu. Max drawdown to największy taki spadek w historii. Kluczowy wskaźnik ryzyka — duży drawdown niszczy psychikę i trudno go odrobić.', category: 'Ogólne' },
  { slug: 'equity-curve', term: 'Equity Curve', short: 'Wykres pokazujący wzrost lub spadek wartości konta w czasie.', full: 'Equity curve to graficzne przedstawienie historii wyników konta. Rosnąca, równa linia to cel każdego tradera. Duże wahania oznaczają niestabilną strategię lub problemy z zarządzaniem ryzykiem. Analiza equity curve pomaga ocenić jakość systemu tradingowego.', category: 'Ogólne' },
  { slug: 'setup', term: 'Setup', short: 'Określony układ warunków rynkowych sygnalizujący potencjalną transakcję.', full: 'Setup to zestaw warunków które muszą być spełnione żeby trader rozważył wejście w pozycję. Może obejmować poziom cenowy, formację świecową, sygnał z wskaźnika lub układ stref. Dobry trader handluje tylko gdy setup jest kompletny — bez wyjątków.', category: 'Ogólne' },
  { slug: 'edge', term: 'Edge (przewaga)', short: 'Statystyczna przewaga strategii nad rynkiem w długim terminie.', full: 'Edge to matematyczna przewaga twojego systemu nad rynkiem. Oznacza że przy wystarczającej liczbie transakcji twoja strategia generuje zyski. Znalezienie i utrzymanie edge jest celem każdego tradera — bez niego trading to tylko drogi hazard.', category: 'Ogólne' },
  { slug: 'lot', term: 'Lot', short: 'Standardowa jednostka wolumenu transakcji.', full: 'Lot to standardowa miara wielkości pozycji. 1 lot na Forexie = 100 000 jednostek waluty bazowej. Mini lot = 0.1 lota = 10 000 jednostek. Micro lot = 0.01 lota = 1 000 jednostek. Rozmiar lota bezpośrednio wpływa na wartość pipsa i ryzyko transakcji.', category: 'Ogólne' },
  { slug: 'position-sizing', term: 'Position Sizing', short: 'Dobór wielkości pozycji w zależności od ryzyka i kapitału.', full: 'Position sizing to proces obliczania optymalnej wielkości pozycji. Prawidłowe position sizing gwarantuje że każda transakcja ryzykuje określony procent kapitału (np. 1-2%). Wzór: (Kapitał × %ryzyka) / (odległość SL w pipsach × wartość pipsa).', category: 'Ogólne' },
  { slug: 'backtesting', term: 'Backtesting', short: 'Testowanie strategii na danych historycznych.', full: 'Backtesting to sprawdzanie jak strategia tradingowa działałaby w przeszłości. Pozwala ocenić win rate, profit factor i max drawdown bez ryzykowania prawdziwych pieniędzy. Wyniki backtestu nie gwarantują przyszłych wyników, ale dają statystyczny obraz strategii.', category: 'Ogólne' },
  { slug: 'revenge-trading', term: 'Revenge Trading', short: 'Emocjonalne wchodzenie w transakcje po stracie w celu odegrania się.', full: 'Revenge trading to jeden z najgroźniejszych nawyków tradera. Po stracie pojawia się chęć natychmiastowego odegrania się — trader otwiera nowe pozycje bez czekania na setup, często z większym ryzykiem. Prowadzi do spirali strat. Rozwiązanie: obowiązkowa przerwa po każdej stracie powyżej dziennego limitu.', category: 'Ogólne' },
  { slug: 'fomo', term: 'FOMO', short: 'Fear Of Missing Out — strach przed przegapieniem ruchu.', full: 'FOMO to emocja która pcha tradera do wchodzenia w transakcje gdy rynek już mocno się ruszył. "Kurs leci w górę, muszę wejść!" — zwykle kończy się kupnem na szczycie. Antidotum: jeśli przegapiłeś setup, czekaj na kolejny. Na rynku zawsze będą nowe okazje.', category: 'Ogólne' },
  { slug: 'pip', term: 'Pip', short: 'Najmniejsza standardowa jednostka zmiany ceny w parze walutowej.', full: 'Pip (Percentage in Point) to czwarte miejsce po przecinku dla większości par walutowych (0.0001). Dla par z JPY to drugie miejsce (0.01). Wartość pipsa zależy od pary i wielkości pozycji — przy 1 locie EURUSD 1 pip = ~10 USD.', category: 'Forex' },
  { slug: 'spread', term: 'Spread', short: 'Różnica między ceną kupna (ask) a ceną sprzedaży (bid).', full: 'Spread to koszt transakcji w Forexie — różnica między ceną po jakiej kupujesz (ask) a ceną po jakiej sprzedajesz (bid). Spread 1.5 pipsa oznacza że transakcja zaczyna się od razu na minusie o 1.5 pipsa. Na głównych parach spread jest najniższy.', category: 'Forex' },
  { slug: 'dzwignia', term: 'Dźwignia finansowa (Leverage)', short: 'Możliwość kontrolowania większej pozycji niż posiadany kapitał.', full: 'Dźwignia pozwala kontrolować duże pozycje małym kapitałem. Dźwignia 1:100 oznacza że 1000 zł kontroluje pozycję wartą 100 000 zł. To miecz obosieczny — amplifikuje zarówno zyski jak i straty. W UE brokerzy są ograniczeni do max 1:30 dla retailu.', category: 'Forex' },
  { slug: 'pary-walutowe', term: 'Pary walutowe', short: 'Instrument Forexowy wyrażający wartość jednej waluty w stosunku do drugiej.', full: 'Pary walutowe dzielą się na: Major (EUR/USD, GBP/USD, USD/JPY — najwyższa płynność), Minor (pary bez USD np. EUR/GBP) i Egzotyczne (pary z walutami emerging markets — wysoki spread, niska płynność). Większość day traderów skupia się na Majorach.', category: 'Forex' },
  { slug: 'swap', term: 'Swap (Rollover)', short: 'Dzienny koszt lub przychód za przetrzymanie pozycji przez noc.', full: 'Swap to odsetki naliczane lub dodawane gdy pozycja pozostaje otwarta przez noc. Wynika z różnicy stóp procentowych między walutami. Przy pozycjach day tradingowych zamykanych tego samego dnia swap nie ma znaczenia. Dla swing traderów może być istotnym kosztem lub przychodem.', category: 'Forex' },
  { slug: 'sesja-rynkowa', term: 'Sesja rynkowa', short: 'Godziny aktywności głównych rynków walutowych na świecie.', full: 'Forex działa 24/5. Główne sesje: Azjatycka (00:00-09:00 CET) — niska zmienność, Sydney i Tokio. Londyńska (08:00-17:00 CET) — największa płynność. Nowojorska (13:00-22:00 CET) — duża zmienność. Nakładanie się sesji londyńskiej i nowojorskiej (13:00-17:00) to najlepsza pora dla day tradingu.', category: 'Forex' },
  { slug: 'margin', term: 'Margin', short: 'Zabezpieczenie wymagane przez brokera do otwarcia pozycji z dźwignią.', full: 'Margin to kwota zablokowana przez brokera jako zabezpieczenie pozycji lewarowanej. Przy dźwigni 1:100 i pozycji 100 000 EUR margin wynosi 1 000 EUR. Margin call następuje gdy straty pochłoną zbyt dużą część depozytu — broker automatycznie zamyka pozycje.', category: 'Forex' },
  { slug: 'korelacja-walut', term: 'Korelacja walut', short: 'Stopień w jakim dwie pary walutowe poruszają się w tym samym kierunku.', full: 'Korelacja mierzy jak bardzo ruchy dwóch par są ze sobą powiązane. EUR/USD i GBP/USD mają wysoką korelację dodatnią (~0.85) — poruszają się razem. EUR/USD i USD/CHF mają korelację ujemną — poruszają się przeciwnie. Ważne przy otwieraniu wielu pozycji jednocześnie.', category: 'Forex' },
  { slug: 'altcoin', term: 'Altcoin', short: 'Każda kryptowaluta inna niż Bitcoin.', full: 'Altcoin (Alternative Coin) to każda kryptowaluta poza Bitcoinem. Ethereum jest największym altcoinem. Altcoiny zwykle wykazują wyższą zmienność niż BTC i często poruszają się w korelacji z nim. W czasie "alt season" altcoiny rosną mocniej niż Bitcoin.', category: 'Krypto' },
  { slug: 'halving', term: 'Halving', short: 'Zmniejszenie nagrody za wydobycie bloku Bitcoina o połowę, co ~4 lata.', full: 'Bitcoin Halving to zdarzenie co ~210 000 bloków (~4 lata) kiedy nagroda dla minerów jest zmniejszana o połowę. Redukuje podaż nowych BTC. Historycznie halvingi poprzedzały duże wzrosty ceny — ale przeszłe wyniki nie gwarantują przyszłości. Ostatni halving był w 2024 roku.', category: 'Krypto' },
  { slug: 'dominacja-btc', term: 'Dominacja BTC', short: 'Procentowy udział Bitcoina w całkowitej kapitalizacji rynku krypto.', full: 'Bitcoin Dominance (BTC.D) mierzy jaki procent całego rynku krypto stanowi Bitcoin. Rosnąca dominacja zwykle oznacza odpływ kapitału z altcoinów do BTC (tzw. "Bitcoin season"). Spadająca dominacja to sygnał że kapitał płynie do altcoinów ("alt season"). Kluczowy wskaźnik dla traderów krypto.', category: 'Krypto' },
  { slug: 'on-chain-analiza', term: 'On-chain analiza', short: 'Analiza danych bezpośrednio z blockchainu — przepływy, adresy, wolumeny.', full: 'On-chain analiza to badanie danych publicznych zapisanych w blockchainie. Obejmuje: salda giełd (duże wypływy BTC z giełd = sygnał akumulacji), adresy wielorybów, SOPR (Spent Output Profit Ratio), NVT ratio i inne metryki. Uzupełnia analizę techniczną o fundamentalne dane sieciowe.', category: 'Krypto' },
  { slug: 'funding-rate', term: 'Funding Rate', short: 'Opłata między traderami long i short na rynku perpetual futures.', full: 'Funding rate to mechanizm utrzymujący cenę kontraktu perpetual blisko ceny spot. Gdy funding jest wysoki i dodatni — za dużo longów, rynek może się odwrócić. Ujemny funding — za dużo shortów. Ekstremalnie wysoki lub niski funding często sygnalizuje lokalne szczyty lub dołki.', category: 'Krypto' },
  { slug: 'likwidacja', term: 'Likwidacja', short: 'Przymusowe zamknięcie pozycji lewarowanej gdy kapitał nie pokrywa strat.', full: 'Likwidacja następuje gdy straty na pozycji lewarowanej pochłoną cały margin. Przy dźwigni 10x i spadku o 10% konto jest likwidowane — tracisz cały depozyt. Na rynku krypto likwidacje kaskadowe (duże poziomy likwidacji) mogą powodować gwałtowne ruchy ceny.', category: 'Krypto' },
  { slug: 'stablecoin', term: 'Stablecoin', short: 'Kryptowaluta powiązana z aktywem o stabilnej wartości, najczęściej USD.', full: 'Stablecoiny to kryptowaluty utrzymujące stałą wartość — USDT, USDC, BUSD są powiązane z dolarem 1:1. Używane do: parkowania kapitału bez wychodzenia z rynku, handlu na giełdach bez fiat, unikania zmienności. Stanowią "gotówkę" rynku krypto.', category: 'Krypto' },
  { slug: 'kontrakt-futures', term: 'Kontrakt futures', short: 'Umowa zobowiązująca do kupna/sprzedaży aktywa w przyszłości po ustalonej cenie.', full: 'Futures to standaryzowane kontrakty giełdowe na dostawę aktywa w określonej dacie. W tradingu na indeksy i surowce pozycje są rozliczane gotówkowo (cash-settled). Futures mają datę wygaśnięcia — trzeba rolować pozycję lub zamknąć przed expiracją.', category: 'Futures/Indeksy' },
  { slug: 'nas100', term: 'NAS100 (Nasdaq 100)', short: 'Indeks 100 największych spółek technologicznych notowanych na Nasdaq.', full: 'Nasdaq 100 to jeden z najpopularniejszych instrumentów wśród day traderów. Skupia największe spółki tech: Apple, Microsoft, Nvidia, Amazon, Meta. Charakteryzuje się wysoką zmiennością i bardzo dobrą płynnością. Handluje się nim przez CFD, futures (NQ) lub ETF (QQQ).', category: 'Futures/Indeksy' },
  { slug: 'sp500', term: 'S&P 500', short: 'Indeks 500 największych spółek notowanych na giełdach amerykańskich.', full: 'S&P 500 to najpopularniejszy barometr rynku akcji USA. Zawiera 500 największych spółek z NYSE i Nasdaq ważonych kapitalizacją. Futures na S&P 500 (ES — e-mini, MES — micro) są jednymi z najbardziej płynnych instrumentów na świecie. Kluczowy wskaźnik risk-on/risk-off.', category: 'Futures/Indeksy' },
  { slug: 'kontango-backwardacja', term: 'Kontango i Backwardacja', short: 'Relacja między ceną futures a ceną spot aktywa.', full: 'Kontango: cena futures > cena spot (normalna sytuacja — koszt przechowywania). Backwardacja: cena futures < cena spot (rynek spodziewa się spadków cen lub jest silny popyt spot). Ważne przy rolowaniu kontraktów na surowce i przy długoterminowym trzymaniu pozycji futures.', category: 'Futures/Indeksy' },
  { slug: 'rollover', term: 'Rollover', short: 'Zamknięcie wygasającego kontraktu futures i otwarcie nowego z późniejszą datą.', full: 'Rollover to przeniesienie pozycji futures z wygasającego kontraktu na kolejny. Ważny przy handlu kontraktami na indeksy, surowce i waluty. W okolicach daty rolowania może wystąpić zwiększona zmienność i luki cenowe. Brokerzy często robią rollover automatycznie.', category: 'Futures/Indeksy' },
  { slug: 'vix', term: 'VIX (Indeks Strachu)', short: 'Indeks mierzący oczekiwaną zmienność rynku akcji USA.', full: 'VIX to indeks zmienności S&P 500 obliczany na podstawie cen opcji. VIX powyżej 30 = wysoka zmienność, panika na rynku. VIX poniżej 15 = spokojny rynek, samozadowolenie. Wysoki VIX często towarzyszy dołkom rynkowym. Day traderzy obserwują VIX jako wskaźnik ryzyka rynkowego.', category: 'Futures/Indeksy' },
  { slug: 'gap', term: 'Gap (Luka)', short: 'Przestrzeń na wykresie gdzie cena przeskoczyła bez transakcji.', full: 'Gap powstaje gdy cena otwarcia sesji różni się znacząco od ceny zamknięcia poprzedniej. Typowe w akcjach po wynikach finansowych i na indeksach po weekendzie. Gaps często (ale nie zawsze) są "wypełniane" — cena wraca do poziomu gdzie gap powstał. Gap up przy silnym trendzie to sygnał siły.', category: 'Futures/Indeksy' },
  { slug: 'tick', term: 'Tick', short: 'Minimalna możliwa zmiana ceny kontraktu futures.', full: 'Tick to najmniejszy możliwy ruch ceny danego instrumentu. Dla E-mini S&P 500 (ES) 1 tick = 0.25 punktu = $12.50. Dla NAS100 micro (MNQ) 1 tick = 0.25 punktu = $0.50. Znajomość wartości ticka jest niezbędna do prawidłowego position sizingu na futures.', category: 'Futures/Indeksy' },
  { slug: 'support-resistance', term: 'Support i Resistance', short: 'Poziomy cenowe gdzie popyt (support) lub podaż (resistance) historycznie dominowały.', full: 'Support to poziom gdzie cena wielokrotnie odbijała w górę — silny popyt. Resistance to poziom gdzie cena wielokrotnie odbijała w dół — silna podaż. Po przebiciu support staje się resistance i odwrotnie (role reversal). Kluczowe poziomy S/R to podstawa analizy technicznej w każdym stylu tradingu.', category: 'Ogólne' },
  { slug: 'trend', term: 'Trend', short: 'Dominujący kierunek ruchu ceny w określonym czasie.', full: 'Trend wzrostowy (uptrend): seria wyższych szczytów i wyższych dołków. Trend spadkowy (downtrend): seria niższych szczytów i niższych dołków. Trend boczny (ranging/konsolidacja): cena porusza się w przedziale. "The trend is your friend" — trading zgodny z trendem ma wyższe prawdopodobieństwo sukcesu.', category: 'Ogólne' },
  { slug: 'swieca-japonska', term: 'Świeca japońska', short: 'Graficzne przedstawienie ruchu ceny w danym przedziale czasowym.', full: 'Świeca japońska pokazuje 4 wartości: Open (otwarcie), High (szczyt), Low (dołek), Close (zamknięcie). Zielona/biała świeca = close > open (wzrost). Czerwona/czarna = close < open (spadek). Korpus świecy to różnica O/C, knoty (wicks) pokazują extrema. Formacje świecowe (doji, pin bar, engulfing) są sygnałami tradingowymi.', category: 'Ogólne' },
  { slug: 'glowa-i-ramiona', term: 'Formacja Głowa i Ramiona', short: 'Wzór odwrócenia trendu złożony z trzech szczytów (lub dołków).', full: 'Head and Shoulders to jedna z najbardziej znanych formacji odwrócenia. Składa się z lewego ramienia, głowy (najwyższy szczyt) i prawego ramienia. Przebicie linii szyi (neckline) potwierdzają formację. Odwrócona wersja (Inverse H&S) sygnalizuje zakończenie trendu spadkowego.', category: 'Ogólne' },
  { slug: 'moving-average', term: 'Moving Average (MA)', short: 'Wskaźnik wygładzający cenę przez uśrednianie wartości z okresu.', full: 'Moving Average to jeden z najpopularniejszych wskaźników. SMA (Simple) — prosta średnia z N świec. EMA (Exponential) — ważona, bardziej reaguje na ostatnie ceny. Popularne ustawienia: EMA 20 (krótkoterminowy trend), EMA 50 (średnioterminowy), EMA 200 (długoterminowy). Przecięcia MA generują sygnały kupna/sprzedaży.', category: 'Ogólne' },
  { slug: 'rsi', term: 'RSI (Relative Strength Index)', short: 'Oscylator mierzący siłę i prędkość ruchów ceny (0-100).', full: 'RSI mierzy siłę ruchów cenowych. Wartość powyżej 70 = wykupienie (możliwy zwrot w dół). Poniżej 30 = wyprzedanie (możliwy zwrot w górę). Dywergencja RSI (cena robi nowy szczyt ale RSI nie) to jeden z silniejszych sygnałów słabnącego trendu. Popularne ustawienie: RSI(14).', category: 'Ogólne' },
  { slug: 'wolumen', term: 'Wolumen', short: 'Liczba transakcji (lub kontraktów) zawartych w danym okresie.', full: 'Wolumen potwierdza lub zaprzecza ruchom cenowym. Wzrost ceny przy wysokim wolumenie = silny ruch, instytucje uczestniczą. Wzrost ceny przy niskim wolumenie = słaby ruch, możliwy fakeout. "Volume precedes price" — zmiany wolumenu często wyprzedzają zmiany ceny.', category: 'Ogólne' },
  { slug: 'fibonacci', term: 'Fibonacci Retracement', short: 'Poziomy oporu/wsparcia wyznaczane na podstawie ciągu Fibonacciego.', full: 'Fibonacci retracement wyznacza poziomy korekty w trendzie. Kluczowe poziomy: 23.6%, 38.2%, 50%, 61.8% (złoty stosunek), 78.6%. Najsilniejszym wsparciem jest strefa 61.8-78.6% — "golden pocket". Używane do wyznaczania entry po korekcie w trendzie.', category: 'Ogólne' },
  { slug: 'supply-demand', term: 'Strefa Supply i Demand', short: 'Obszary cenowe gdzie historycznie dominowała podaż lub popyt instytucjonalny.', full: 'Supply zone (strefa podaży) to obszar gdzie duzi gracze sprzedawali — cena dynamicznie z niego spadła. Demand zone (strefa popytu) to obszar gdzie kupowali — cena dynamicznie wzrosła. Cena często wraca do tych stref zanim kontynuuje ruch. Podstawa smart money concepts (SMC).', category: 'Ogólne' },
  { slug: 'break-of-structure', term: 'Break of Structure (BOS)', short: 'Przebicie poprzedniego szczytu lub dołka potwierdzające zmianę struktury rynku.', full: 'Break of Structure to przebicie kluczowego poziomu struktury rynku — poprzedniego szczytu (w uptrend) lub poprzedniego dołka (w downtrend). BOS potwierdza kontynuację trendu. Jego odwrotność — Change of Character (CHoCH) — sygnalizuje możliwą zmianę trendu. Kluczowe pojęcia w SMC.', category: 'Ogólne' },
  { slug: 'liquidity', term: 'Liquidity (Płynność)', short: 'Obszary cenowe gdzie gromadzą się zlecenia stop — cele dla dużych graczy.', full: 'W smart money concepts płynność to skupiska zleceń stop loss (equal highs/lows, poprzednie szczyty/dołki). Duzi gracze (instytucje) potrzebują płynności do wypełnienia swoich dużych pozycji — celują w te poziomy. "Sweep of liquidity" (wybicie i powrót) to typowy ruch przed właściwym kierunkiem.', category: 'Ogólne' },

];
